services:
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_PASSWORD: ${SJSUBARK_PSQL_PASSWORD} 
      POSTGRES_USER: ${SJSUBARK_PSQL_USER} 
      POSTGRES_DB: ${SJSUBARK_PSQL_DB} 
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: 
